CREATE TABLE roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE user_entity
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login      VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    nickname   VARCHAR(255),
    password   VARCHAR(255),
    gender     INTEGER,
    CONSTRAINT pk_userentity PRIMARY KEY (id)
);

ALTER TABLE user_entity
    ADD CONSTRAINT uc_userentity_login UNIQUE (login);

ALTER TABLE user_entity
    ADD CONSTRAINT uc_userentity_nickname UNIQUE (nickname);